In [1]:
import numpy as np

In [3]:
from numpy.linalg import inv
#Matriz de coeficientes
a = np.array([[1,1,1],
              [1,2,4],
              [1,3,9]])
a.shape

(3, 3)

In [4]:
#Matriz de terminos independientes
b = np.array([4,0,12])
b

array([ 4,  0, 12])

## Formula :  Ax = B

In [6]:
inv(a)

array([[ 3. , -3. ,  1. ],
       [-2.5,  4. , -1.5],
       [ 0.5, -1. ,  0.5]])

In [5]:
x = inv(a).dot(b)
x

array([ 24., -28.,   8.])

## Combinación Lineal

Una combinación lineal de $x_1,x_2,..., x_n$ tiene la forma :  $a_1x_1 + a_2x_2 + ... + a_nx_n$

Una ecuación lienal de $x_1,x_2,..., x_n$ variable tiene la forma : $a_1x_1 + a_2x_2 + ... + a_nx_n = d$  donde $a_1,...,a_n \in \mathbb{R}$

## Sistema de ecuación lineal

$\frac{1}{4}x + y - z  = 0$ 

$x + 4y + 2z = 12$

$2x - 3y - z = 3$ 

In [9]:
a = np.array([[0.25,1,-1],[1,4,2],[2,-3,-1]]) #matriz de coeficientes
b = np.array([0,12,3])  #matriz de terminos independientes

In [11]:
x = inv(a).dot(b)
x

array([4., 1., 2.])

## Rango de una matriz

Es el mayor de los ordenes de los menores no nulos que podemos encontrar en la matriz

In [12]:
a = np.array([[1,1,0],[0,1,1],[1,0,1],[5,-1,1]])
b = np.array([3,5,4,6])

In [39]:
from numpy.linalg import *
#Rango de la matriz de coeficientes
matrix_rank(a)

3

In [37]:
#Matriz ampliada
matrix_ampliado = np.zeros((4,4))
for w in range(4):
    matrix_ampliado[w] = np.append(a[w],b[w])
matrix_ampliado

array([[ 1.,  1.,  0.,  3.],
       [ 0.,  1.,  1.,  5.],
       [ 1.,  0.,  1.,  4.],
       [ 5., -1.,  1.,  6.]])

In [38]:
#Rango de la matriz ampliada
matrix_rank(matrix_ampliado)

3

$\textit{Si el rango de la matriz de coeficiente es igual al rango de la matriz ampliada entonces el sistema es compatible}$

$\textit{Entonces se cumple} :$  $r(A) = r(A|B) = n $ donde n es el numero de incognitas

$cs : (1,2,3)$ En ambos casos por lo que ambos sistemas son equivalentes

In [48]:
#Forma escalonada de la matriz ampliada
#np.info(np.linalg.solve)


LinAlgError: Last 2 dimensions of the array must be square

## Factorizaciones triangulares