In [1]:
import numpy as np

In [3]:
from numpy.linalg import inv
#Matriz de coeficientes
a = np.array([[1,1,1],
              [1,2,4],
              [1,3,9]])
a.shape

(3, 3)

In [4]:
#Matriz de terminos independientes
b = np.array([4,0,12])
b

array([ 4,  0, 12])

## Formula :  Ax = B

In [6]:
inv(a)

array([[ 3. , -3. ,  1. ],
       [-2.5,  4. , -1.5],
       [ 0.5, -1. ,  0.5]])

In [5]:
x = inv(a).dot(b)
x

array([ 24., -28.,   8.])

## Combinación Lineal

Una combinación lineal de $x_1,x_2,..., x_n$ tiene la forma :  $a_1x_1 + a_2x_2 + ... + a_nx_n$

Una ecuación lienal de $x_1,x_2,..., x_n$ variable tiene la forma : $a_1x_1 + a_2x_2 + ... + a_nx_n = d$  donde $a_1,...,a_n \in \mathbb{R}$

## Sistema de ecuación lineal


$\left \{
\begin{array}{l}
\frac{1}{4}x + y - z  = 0 \\
x + 4y + 2z = 12 \\
2x - 3y - z = 3
\end{array}
\right.$


In [10]:
a = np.array([[0.25,1,-1],[1,4,2],[2,-3,-1]]) #matriz de coeficientes
b = np.array([0,12,3])  #matriz de terminos independientes

In [15]:
inv(a)

array([[ 0.12121212,  0.24242424,  0.36363636],
       [ 0.3030303 ,  0.10606061, -0.09090909],
       [-0.66666667,  0.16666667, -0.        ]])

In [16]:
x = inv(a).dot(b)
x

array([4., 1., 2.])

## Rango de una matriz

Es el mayor de los ordenes de los menores no nulos que podemos encontrar en la matriz

In [35]:
a = np.array([[3,4,-2],[2,-3,4],[1,-2,3]])
b = np.array([0,11,7])

In [36]:
from numpy.linalg import *
#Rango de la matriz de coeficientes
matrix_rank(a)

3

In [37]:
a.shape

(3, 3)

In [38]:
#Matriz ampliada
matrix_ampliado = np.zeros((3,4))
for w in range(3):
    matrix_ampliado[w] = np.append(a[w],b[w])
matrix_ampliado

array([[ 3.,  4., -2.,  0.],
       [ 2., -3.,  4., 11.],
       [ 1., -2.,  3.,  7.]])

In [39]:
#Rango de la matriz ampliada
matrix_rank(matrix_ampliado)

3

$\textit{Si el rango de la matriz de coeficiente es igual al rango de la matriz ampliada entonces el sistema es compatible}$

$\textit{Entonces se cumple} :$  $r(A) = r(A|B) = n $ donde n es el numero de incognitas

$c.s : \{(2,-1,1)\}$ En ambos casos por lo que ambos sistemas son equivalentes

In [42]:
#Forma escalonada de la matriz ampliada
#np.info(np.linalg.solve)
x  = np.linalg.solve(a,b)
x

array([ 2., -1.,  1.])

## Factorizaciones triangulares
Sea $A \in M_{4}(\mathbb{R})$ donde 

\begin{bmatrix} 
1 & -1 & 2 & 4 \\ 
-2 & 0 & 5 & 5 \\ 
1 & 1 & 2 & -3 \\
3 & 3 & 4 & 0
\end{bmatrix}

In [51]:
#Creando la matriz A
a = np.array([[1,-1,2,4],[-2,0,5,5],[1,1,2,-3],[3,3,4,0]])
a

array([[ 1, -1,  2,  4],
       [-2,  0,  5,  5],
       [ 1,  1,  2, -3],
       [ 3,  3,  4,  0]])

In [53]:
from scipy.linalg import lu
#Matriz triangular superior equivalente
p,l,u = lu(a)

In [56]:
u

array([[ 3.        ,  3.        ,  4.        ,  0.        ],
       [ 0.        ,  2.        ,  7.66666667,  5.        ],
       [ 0.        ,  0.        ,  8.33333333,  9.        ],
       [ 0.        ,  0.        ,  0.        , -3.72      ]])

In [60]:
#Matriz triangular inferior equivalente
np.dot(p,l)

array([[ 3.33333333e-01, -1.00000000e+00,  1.00000000e+00,
         0.00000000e+00],
       [-6.66666667e-01,  1.00000000e+00,  0.00000000e+00,
         0.00000000e+00],
       [ 3.33333333e-01,  2.77555756e-17,  8.00000000e-02,
         1.00000000e+00],
       [ 1.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00]])

## Formula: A = LU
Donde $L$ es la matriz triangular inferior y $U$ es la matriz triangular superior

In [61]:
np.allclose(a,p@l@u)

True